apps/presupuestos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='presupuestos'

urlpatterns = [

    url(regex=r"^registrar$", view=crear_presupuesto, name="registrar_presupuesto"),
    url(regex=r"^listado$", view=mis_presupuestos, name="listado_de_presupuestos"),
    url(r'^editar/(?P<pk>\d+)/$', view=EditarPresupuesto.as_view(), name='editar_presupuesto'),
    url(r'^desactivar/(?P<id_presupuesto>\d+)/$', view=desactivar_presupuesto, name='desactivar_presupuesto'),
    url(regex=r"^registrar_categoria/(?P<id_presupuesto>[\w-]+)$", view=crear_categoria, name="registrar_categoria"),
    url(regex=r"^listado_de_categorias/(?P<id_presupuesto>[\w-]+)$", view=listado_de_categorias_del_presupuesto, name="listado_de_categorias"),
    url(regex=r"^editar_categoria/(?P<pk>[\w-]+)$", view=EditarCategoriaF, name="editar_categoria"),
]

apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='usuarios'

urlpatterns = [
    url('signup', signup, name='signup'),
    url('inicio', view=Inicio, name='inicio'),
    path('cuentas_y_saldo', vista_cuentas_y_saldo, name="cuentas_y_saldo"),
    path('cuentas_y_saldo_json', cuentas_y_saldo_json, name="cuentas_y_saldo_json"),
    path('getGraficPie', view=getGraficPie, name="getGraficPie"),
    path('getCuentas', view=getCuentas, name="getCuentas"),
    ]

ds2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include, handler404
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include ('apps.cuentas.urls', namespace='cuentas')),
    path('presupuestos/', include ('apps.presupuestos.urls', namespace='presupuestos')),
    path('usuarios/', include ('apps.usuarios.urls', namespace='usuarios')),
    path('transacciones/', include ('apps.transacciones.urls', namespace='transacciones')),

    path('', views.LoginView.as_view(), name='home' ),
    url(r'^accounts/', include('allauth.urls'), name='accounts'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),   

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/presupuestos/models.py
from django.db import models
from django.utils import timezone

from apps.usuarios.models import User

class Presupuesto(models.Model):
	TIPOS=(
		('Egreso','Egreso'),
		('Ingreso','Ingreso'),
		)
	ESTADOS=(
		('Activo','Activo'),
		('Inactivo','Inactivo'),
		)

	nombre = models.CharField(max_length=30, verbose_name="Nombre del presupuesto")#universidad
	mes = models.DateField(editable=False)#agosto
	total_planeado = models.IntegerField()
	total_actual =models.IntegerField()
	tipo = models.CharField(max_length=20,choices=TIPOS, default="Egreso")
	estado = models.CharField(max_length=20,choices=ESTADOS, default="Activo")
	usuario = models.ForeignKey(User, related_name="presupuestos_del_usuario", on_delete=models.CASCADE)

	def __str__(self):

		return ("%s %s (%s)"%(self.nombre, self.total_planeado, self.total_actual))

	def save(self, *args, **kwargs):

		if not self.id:
			self.mes = timezone.now()
		return super(Presupuesto, self).save(*args, **kwargs)

class Categoria(models.Model):

	nombre = models.CharField(max_length=30, verbose_name="Nombre de la categoría") #almuerzos
	planeado = models.IntegerField()#20000
	actual = models.IntegerField()
	diferencia = models.IntegerField()
	presupuesto = models.ForeignKey(Presupuesto, related_name="categorias_del_presupuesto", on_delete=models.CASCADE)

	def __str__(self):
		return ("%s "%(self.nombre))

apps/presupuestos/forms.py
from django import forms

from .models import Presupuesto, Categoria

class PresupuestoForm(forms.ModelForm):
	class Meta:
		model = Presupuesto
		fields = ("nombre", "tipo",)
		labels = {
		"nombre": "Nombre: ", 
		"tipo":"Tipo:",
		}

	def clean_nombre(self):
		data = self.cleaned_data.get('nombre')
		return data


	def clean_tipo(self):
		data = self.cleaned_data.get('tipo')
		return data


class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria
		fields= ("nombre", "planeado", )
		labels = {
		"nombre" : "Nombre: ",
		"planeado" : "Planeado: "
		}

	def clean_nombre(self):
		data = self.cleaned_data.get('nombre')
		return data
	def clean_planeado(self):
		data = self.cleaned_data.get('planeado')
		return data

apps/presupuestos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .models import Presupuesto, Categoria
from .forms import PresupuestoForm, CategoriaForm

@login_required
def crear_presupuesto(request):
    if request.method == 'POST':
        form = PresupuestoForm(request.POST)
        if form.is_valid():
            presupuesto = form.save(commit=False)
            presupuesto.nombre = form.cleaned_data["nombre"]
            presupuesto.total_planeado = 0
            presupuesto.total_actual = 0
            presupuesto.usuario = request.user
            presupuesto.save()
            messages.success(request, 'El presupuesto se registró correctamente.')
            return redirect('presupuestos:registrar_categoria', id_presupuesto=presupuesto.id)
        else:
            messages.error(request, 'No se pudo registrar el presupuesto, por favor verifique los datos ingresados.')
    else:
        form = PresupuestoForm()
    return render(request, 'presupuestos/presupuestos_form.html', {
        'form': form
    })


@login_required
def mis_presupuestos(request):
    presupuestos = request.user.presupuestos_del_usuario.filter(estado="Activo")
    return render(request, 'presupuestos/listado_de_presupuestos.html',{'presupuestos':presupuestos})


class EditarPresupuesto(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Presupuesto
    form_class = PresupuestoForm
    template_name = 'presupuestos/presupuesto_editar.html'
    success_message = "El presupuesto %(nombre) s se modificó correctamente."
    success_url = reverse_lazy('presupuestos:listado_de_presupuestos')

@login_required
def desactivar_presupuesto(request, id_presupuesto):
    presupuesto = get_object_or_404(Presupuesto, pk=id_presupuesto)
    presupuesto.estado = "Inactivo"
    presupuesto.save()
    return redirect('presupuestos:listado_de_presupuestos')

@login_required
def crear_categoria(request, id_presupuesto):
    presupuesto = get_object_or_404(Presupuesto, pk=id_presupuesto)
    form_class = CategoriaForm
    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            categoria = form.save(commit=False)
            categoria.presupuesto = presupuesto
            categoria.nombre = form.cleaned_data["nombre"]
            categoria.planeado = form.cleaned_data["planeado"]
            categoria.actual = 0
            categoria.diferencia = form.cleaned_data["planeado"]
            presupuesto.total_planeado += categoria.planeado
            categoria.save()
            presupuesto.save()
            messages.success(request, 'La categoria se registró correctamente.')
            return redirect('presupuestos:listado_de_categorias', id_presupuesto)
        else:
            messages.error(request, "Error")
    return render(request, 'presupuestos/categorias_form.html', {'form':form_class(), 'id_presupuesto':id_presupuesto})


@login_required
def listado_de_categorias_del_presupuesto(request, id_presupuesto):
    presupuesto = get_object_or_404(Presupuesto, pk=id_presupuesto)
    categorias = presupuesto.categorias_del_presupuesto.all()
    nombre_presupuesto = presupuesto.nombre
    return render(request, 'presupuestos/listado_de_categorias.html',{'categorias':categorias, 
        'nombre_presupuesto': nombre_presupuesto, 'id_presupuesto':id_presupuesto})

@login_required
def EditarCategoriaF(request,pk):
    categoria = Categoria.objects.get(id=pk)
    if request.method == 'GET':
        form = CategoriaForm(instance=categoria)
    else:
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            categoria = form.save(commit=False)
            categoria.diferencia = categoria.planeado
            actualizarCategoria(categoria.id, categoria.planeado)
            categoria.save()
        return redirect('presupuestos:listado_de_categorias', categoria.presupuesto.id)
    return render(request, 'presupuestos/categoria_editar.html', {'form':form, 'id_presupuesto':categoria.presupuesto.id})

def actualizarCategoria(idCategoria, inPlaneado):
    categoriaOld = Categoria.objects.get(id=idCategoria)
    presupuesto = Presupuesto.objects.get(id=str(categoriaOld.presupuesto.id))
    presupuesto.total_planeado -=  categoriaOld.planeado
    presupuesto.total_planeado += inPlaneado
    if categoriaOld.actual != 0:
        categoriaOld.diferencia = (inPlaneado - categoriaOld.actual)
    else:
        print("ENTRO POR AQUI")
        categoriaOld.diferencia = inPlaneado
    categoriaOld.planeado = inPlaneado
    presupuesto.save()
    categoriaOld.save()

templates/presupuestos/categoria_editar.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{{ form_evento.media }}
{% block title %} Editar categoría {% endblock %}
{% block content %}
	<div class="container-fluid">
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Editar categoría</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Editar categoría</h6>
            </div>
            <div class="card-body">
				<form method="post">
					{% csrf_token %}
					{% bootstrap_form form %}
					<a href="{% url 'presupuestos:listado_de_categorias' id_presupuesto %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a>
					<button type="submit" class="btn btn-success btn-icon-split"><span class="icon text-white-50"><i class="fas fa-check"></i></span><span class="text">Guardar</span></button>	
				</form>
			</div>
		</div>
	</div>

{% endblock %}

templates/presupuestos/categorias_form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{{ form_evento.media }}
{% block title %} Registrar categoría {% endblock %}
{% block content %}
	<div class="container-fluid">
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Registrar categoría</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Registrar categoría</h6>
            </div>
            <div class="card-body">
				<form method="post">
					{% csrf_token %}
					{% bootstrap_form form %}
					<a href="{% url 'presupuestos:listado_de_categorias' id_presupuesto %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a>
					<button type="submit" class="btn btn-success btn-icon-split"><span class="icon text-white-50"><i class="fas fa-check"></i></span><span class="text">Guardar</span></button>					
				</form>
			</div>
		</div>
	</div>

{% endblock %}

templates/presupuestos/listado_de_categorias.html
{% extends 'base/tables.html' %}
{% load bootstrap4 %}
{% block title %} Lista de categorías {% endblock %}

{% block content %}
<!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Categorías del presupuesto: {{nombre_presupuesto}}</h1>
          
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <div class="row">
                <div class="col align-items-left">
                  <h6 class="m-0 font-weight-bold text-primary">Lista de categorías del presupuesto:  {{nombre_presupuesto}} </h6>
                </div>
                <div class="col align-items-right">
                <span class="float-right">
                <a href="{% url 'presupuestos:listado_de_presupuestos' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a> <a class="btn btn-success" href="{% url 'presupuestos:registrar_categoria' id_presupuesto %}"> <span class="text"><i class="fas fa-plus-circle"></i> Añadir Categoría</span></a>           
                </span>
                </div>
              </div>                      

            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Planeado</th>
                            <th scope="col">Actual</th>
                            <th scope="col">Diferencia</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if categorias  %}
                        {% for categoria in categorias  %}
                        <tr class="table-primary">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ categoria.nombre }}</td>
                            <td>{{ categoria.planeado }}</td>
                            <td>{{ categoria.actual }}</td>
                            <td>{{ categoria.diferencia }}</td>
                            <td><a class="btn btn-info" href="{% url 'presupuestos:editar_categoria' categoria.id %}"><i class="fas fa-edit"></i> Editar</a>
                            </td>
                            
                        </tr>
                        {% endfor %}
                    {% else %}
                    <h1> No hay categorías </h1>
                    {% endif %}
                    </tbody>
                </table>
                          
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->


{% endblock %}

templates/presupuestos/listado_de_presupuestos.html
{% extends 'base/tables.html' %}
{% load bootstrap4 %}
{% block title %} Lista de presupuestos {% endblock %}

{% block content %}
<!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Presupuestos</h1>
                    
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <div class="row">
                <div class="col align-items-left">
                  <h6 class="m-0 font-weight-bold text-primary">Lista de presupuestos</h6>
                </div>
                <div class="col align-items-right">
                    <span class="float-right">
                      <a href="{% url 'usuarios:inicio' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a> <a class="btn btn-success" href="{% url 'presupuestos:registrar_presupuesto' %}"> <span class="text"><i class="fas fa-plus-circle"></i> Añadir Presupuesto</span></a>
                    </span>
                </div>
              </div>              
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Planeado</th>
                            <th scope="col">Actual</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if presupuestos  %}
                        {% for presupuesto in presupuestos  %}
                        <tr class="table-primary">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ presupuesto.nombre }}</td>
                            <td>{{ presupuesto.total_planeado }}</td>
                            <td>{{ presupuesto.total_actual }}</td>
                            <td width="45%">
                              <!--<a class="btn btn-warning" href="{% url 'presupuestos:editar_presupuesto' presupuesto.id %}"><i class="fas fa-eye"></i> Ver</a>-->
                              <a class="btn btn-info" href="{% url 'presupuestos:editar_presupuesto' presupuesto.id %}"><i class="fas fa-edit"></i> Editar</a>
                              <a class="btn btn-danger" href="{% url 'presupuestos:desactivar_presupuesto' presupuesto.id %}" data-toggle="modal" data-target="#confirmationModal"><i class="fas fa-minus-circle"></i> Inhabilitar</a>
                              <a class="btn btn-icon-split btn-success" href="{% url 'presupuestos:listado_de_categorias' presupuesto.id %}"><span class="text"><i class="fas fa-eye"></i> Ver Categorías</span></a>
                              
                              <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">¿Inhabilitar?</h5>
                                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">×</span>
                                    </button>
                                    </div>
                                  <div class="modal-body">¿Está Seguro que desea inhabilitar el presupuesto <b>{{ presupuesto.nombre }}</b>?</div>
                                  <div class="modal-footer">
                                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                                    <a class="btn btn-danger" href=" {% url 'presupuestos:desactivar_presupuesto' 1 %}">Inhabilitar</a>
                                  </div>
                                </div>
                              </div>
                            </div>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                    <h1> No hay presupuestos </h1>
                    {% endif %}
                    </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->
{% endblock %}

templates/presupuestos/presupuesto_editar.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{{ form_evento.media }}
{% block title %} Editar presupuesto {% endblock %}
{% block content %}
	<div class="container-fluid">
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Editar presupuesto</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Editar presupuesto</h6>
            </div>
            <div class="card-body">
				<form method="post">
					{% csrf_token %}
					{% bootstrap_form form %}
					<a href="{% url 'presupuestos:listado_de_presupuestos' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a>
					<button type="submit" class="btn btn-success btn-icon-split"><span class="icon text-white-50"><i class="fas fa-check"></i></span><span class="text">Guardar</span></button>
				</form>
			</div>
		</div>
	</div>

{% endblock %}

templates/presupuestos/presupuestos_form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{{ form_evento.media }}
{% block title %} Registrar presupuesto {% endblock %}
{% block content %}
	<div class="container-fluid">
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Registrar presupuesto</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Registrar presupuesto</h6>
            </div>
            <div class="card-body">
				<form method="post">
					{% csrf_token %}
					{% bootstrap_form form %}
					<a href="{% url 'presupuestos:listado_de_presupuestos' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a>
					<button type="submit" class="btn btn-success btn-icon-split"><span class="icon text-white-50"><i class="fas fa-check"></i></span><span class="text">Guardar</span></button>
				</form>
			</div>
		</div>
	</div>

{% endblock %}