apps/cuentas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='cuentas'

urlpatterns = [

    url(regex=r"^registrar$", view=crear_cuenta, name="registrar_cuenta"),
    url(regex=r"^listado$", view=mis_cuentas, name="listado_de_cuentas"),
    url(r'^editar/(?P<pk>\d+)/$', view=EditarCuenta.as_view(), name='editar_cuenta'),
    url(r'^ver/(?P<pk>\d+)/$', view=ver_cuenta, name='ver_cuenta'),
    url(r'^getGraficArea/(?P<pk>\d+)/$', view=getGraficArea, name="getGraficArea"),
]

apps/presupuestos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='presupuestos'

urlpatterns = [

    url(regex=r"^registrar$", view=crear_presupuesto, name="registrar_presupuesto"),
    url(regex=r"^listado$", view=mis_presupuestos, name="listado_de_presupuestos"),
    url(r'^editar/(?P<pk>\d+)/$', view=EditarPresupuesto.as_view(), name='editar_presupuesto'),
    url(r'^desactivar/(?P<id_presupuesto>\d+)/$', view=desactivar_presupuesto, name='desactivar_presupuesto'),
    url(regex=r"^registrar_categoria/(?P<id_presupuesto>[\w-]+)$", view=crear_categoria, name="registrar_categoria"),
    url(regex=r"^listado_de_categorias/(?P<id_presupuesto>[\w-]+)$", view=listado_de_categorias_del_presupuesto, name="listado_de_categorias"),
    url(regex=r"^editar_categoria/(?P<pk>[\w-]+)$", view=EditarCategoriaF, name="editar_categoria"),
]

apps/transacciones/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='transacciones'

urlpatterns = [

    url(regex=r"^registrar$", view=crear_transaccion, name="registrar_transaccion"),
    url(regex=r"^registrar_ingreso$", view=crear_ingreso, name="registrar_ingreso"),
    url(regex=r"^registrar_egreso$", view=crear_egreso, name="registrar_egreso"),
    url(regex=r"^listado_ingresos$", view=mis_ingresos, name="listado_de_ingresos"),
    url(regex=r"^listado_egresos$", view=mis_egresos, name="listado_de_egresos"),
 
]

apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='usuarios'

urlpatterns = [
    url('signup', signup, name='signup'),
    url('inicio', view=Inicio, name='inicio'),
    path('cuentas_y_saldo', vista_cuentas_y_saldo, name="cuentas_y_saldo"),
    path('cuentas_y_saldo_json', cuentas_y_saldo_json, name="cuentas_y_saldo_json"),
    path('getGraficPie', view=getGraficPie, name="getGraficPie"),
    path('getCuentas', view=getCuentas, name="getCuentas"),
    ]

ds2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include, handler404
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include ('apps.cuentas.urls', namespace='cuentas')),
    path('presupuestos/', include ('apps.presupuestos.urls', namespace='presupuestos')),
    path('usuarios/', include ('apps.usuarios.urls', namespace='usuarios')),
    path('transacciones/', include ('apps.transacciones.urls', namespace='transacciones')),

    path('', views.LoginView.as_view(), name='home' ),
    url(r'^accounts/', include('allauth.urls'), name='accounts'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),   

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base/base.html
{% load staticfiles %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block extrastatic %}
  {% endblock %}
 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
   <link rel="icon" href="{% static 'img/wallet.png' %}" type="image/gif" sizes="16x16">

  <title>{% block title %} Titulo base {% endblock %}</title>
 {% block extrahead %}
  {% endblock %}
  <!-- Custom fonts for this template-->
  <link href=" {% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href=" {% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <script src=" {% static 'vendor/jquery/jquery.min.js' %}"></script>
  {{ form.media }}
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
    {% block nav %}
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'usuarios:inicio' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-wallet"></i>
        </div>
        <div class="sidebar-brand-text mx-3">EasyWallet </div>
      </a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'usuarios:inicio' %}">
          <i class="fas fa-chart-line"></i>
          <span><b> Inicio </b></span></a>
      </li>
      
      <!-- Divider -->
      <hr class="sidebar-divider my-0">
      <!-- Nav Item - Event Menu -->
      <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-money-check"></i>
          <span>Cuentas</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'cuentas:registrar_cuenta' %}">Registrar Cuenta</a>
            <a class="collapse-item" href="{% url 'cuentas:listado_de_cuentas' %}">Listado de cuentas</a>
          </div>
        </div>
      </li>
      <!-- Divider -->
      <!-- Nav Item - Event Menu -->
      <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo1" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-search-dollar"></i>
          <span>Presupuestos</span>
        </a>
        <div id="collapseTwo1" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'presupuestos:registrar_presupuesto' %}">Crear Presupuesto</a>
            <a class="collapse-item" href="{% url 'presupuestos:listado_de_presupuestos' %}">Listado de presupuestos</a>
          </div>
        </div>
      </li>
      <!-- Divider -->
      <!-- Nav Item - Event Menu -->
      <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo2" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-hand-holding-usd"></i>
          <span>Transacciones</span>
        </a>
        <div id="collapseTwo2" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'transacciones:registrar_ingreso' %}">Registrar Ingreso</a>
            <a class="collapse-item" href="{% url 'transacciones:registrar_egreso' %}">Registrar Egreso</a>
            <a class="collapse-item" href="{% url 'transacciones:listado_de_ingresos' %}">Listado de Ingresos</a>
            <a class="collapse-item" href="{% url 'transacciones:listado_de_egresos' %}">Listado de Egresos</a>            
          </div>
        </div>
      </li>



      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    {% endblock %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
      <!-- Main Content -->
      <div id="content">

        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-0 static-top shadow">
          <div class="sidebar-brand-text mx-3"> <i class="fas fa-user fa-sm fa-fw mr-2 text-primary"></i>Bienvenido, {{request.user}} </div>
          <ul class="navbar-nav ml-auto">
            <a class="nav-link" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal">
              <i class="fas fa-sign-out-alt"></i>
                Cerrar Sesión
            </a>
            <!--<div class="topbar-divider d-none d-sm-block"></div>-->

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">

                  <!--<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user}}</span>
                    <img class="img-profile rounded-circle" >
                  </a>
                  -- Dropdown - User Information --                  
                 <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">
                      <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                      Profile
                    </a>
                    <a class="dropdown-item" href="#">
                      <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                      Settings
                    </a>
                    <a class="dropdown-item" href="#">
                      <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                      Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal">
                      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                      Cerrar Sesión
                    </a>
                  </div>-->
                </li>

            </ul>
          </nav>

{% include 'base/messages.html' %}
{% block content %}
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->
{% endblock %}
      <!-- Footer -->
{% block footer %}
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            
          </div>
        </div>
      </footer>
      <!-- End of Footer -->
{% endblock %}
    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">¿Listo para salir?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">¿Está seguro de salir de la aplicación?</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href=" {% url 'logout' %}">Cerrar Sesión</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src=" {% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src=" {% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src=" {% static 'js/sb-admin-2.min.js' %}"></script>
{% block extrajs %}
{% endblock %}
</body>

</html>

templates/base/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

templates/base/tables.html
{% extends 'base/base.html' %}
{%  load staticfiles %}
{% load bootstrap4 %}

{% block extrahead %}
	<!-- Custom styles for this page -->
	<link href=" {% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}


{% block extrajs %}
	<!-- Page level plugins -->
	<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

	<!-- Page level custom scripts -->
	<script type="text/javascript">
		$('.dataTable').DataTable();
	</script>

{% endblock %}