apps/cuentas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='cuentas'

urlpatterns = [

    url(regex=r"^registrar$", view=crear_cuenta, name="registrar_cuenta"),
    url(regex=r"^listado$", view=mis_cuentas, name="listado_de_cuentas"),
    url(r'^editar/(?P<pk>\d+)/$', view=EditarCuenta.as_view(), name='editar_cuenta'),
    url(r'^ver/(?P<pk>\d+)/$', view=ver_cuenta, name='ver_cuenta'),
    url(r'^getGraficArea/(?P<pk>\d+)/$', view=getGraficArea, name="getGraficArea"),
]

apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='usuarios'

urlpatterns = [
    url('signup', signup, name='signup'),
    url('inicio', view=Inicio, name='inicio'),
    path('cuentas_y_saldo', vista_cuentas_y_saldo, name="cuentas_y_saldo"),
    path('cuentas_y_saldo_json', cuentas_y_saldo_json, name="cuentas_y_saldo_json"),
    path('getGraficPie', view=getGraficPie, name="getGraficPie"),
    path('getCuentas', view=getCuentas, name="getCuentas"),
    ]

ds2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include, handler404
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include ('apps.cuentas.urls', namespace='cuentas')),
    path('presupuestos/', include ('apps.presupuestos.urls', namespace='presupuestos')),
    path('usuarios/', include ('apps.usuarios.urls', namespace='usuarios')),
    path('transacciones/', include ('apps.transacciones.urls', namespace='transacciones')),

    path('', views.LoginView.as_view(), name='home' ),
    url(r'^accounts/', include('allauth.urls'), name='accounts'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),   

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/cuentas/models.py
from django.db import models

from apps.usuarios.models import User

class Cuenta(models.Model):

    TIPO=(
		('Credito', 'Credito'),
		('Debito', 'Debito')
		)

    ESTADO=(
		('Activa', 'Activa'),
		('Inactiva', 'Inactiva')
		)
    
    nombre = models.CharField(max_length=25, verbose_name="Nombre de la cuenta")
    saldo = models.IntegerField()
    tipo = models.CharField(max_length=20, choices=TIPO, default= 'Debito')
    estado = models.CharField(max_length=20, choices=ESTADO, default= 'Activa')
    usuario = models.ForeignKey(User, related_name="cuentas_del_usuario", on_delete=models.CASCADE) 

    def __str__(self):
        return ("%s   %s   (%s)"%(self.nombre, self.tipo, self.saldo))

apps/cuentas/forms.py
from django import forms
from django.core.exceptions import ValidationError
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput
import datetime

from .models import Cuenta

class CuentaForm(forms.ModelForm):

	class Meta:
		model = Cuenta
		fields = ("nombre" , "saldo", "tipo", "estado", )
		labels = {
		"nombre": "Nombre: ",
		"saldo": "Saldo: ", 
		"tipo": "Tipo: ",
		"estado": "Estado: "
		}

	def clean_nombre(self):
		data = self.cleaned_data.get('nombre')
		return data
	def clean_saldo(self):
		data = self.cleaned_data.get('saldo')
		return data
	def clean_tipo(self):
		data = self.cleaned_data.get('tipo')
		return data
	def clean_estado(self):
		data = self.cleaned_data.get('estado')
		return data
class EditarCuentaForm(forms.ModelForm):
	class Meta:
		model = Cuenta
		fields = ("nombre" ,"tipo", "estado", )
		labels = {
		"nombre": "Nombre: ", 
		"tipo": "Tipo: ",
		"estado": "Estado: "
		}

apps/cuentas/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.core.serializers import serialize
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from apps.transacciones.models import Transaccion
from .models import Cuenta
from .forms import CuentaForm, EditarCuentaForm

@login_required
def crear_cuenta(request):
    if request.method == 'POST':
        form = CuentaForm(request.POST)
        if form.is_valid():
            cuenta = form.save(commit=False)
            cuenta.nombre = form.cleaned_data["nombre"]
            cuenta.saldo = form.cleaned_data["saldo"]
            cuenta.tipo = form.cleaned_data["tipo"]
            cuenta.usuario = request.user
            cuenta.save()
            transaccion = Transaccion(descripcion="Inicial",valor=cuenta.saldo, cuenta=cuenta, tipo="Inicial", saldo_actual_cuenta=cuenta.saldo)
            transaccion.save()
            messages.success(request, 'La cuenta se registró correctamente.')
            return redirect('cuentas:listado_de_cuentas')
        else:
            messages.error(request, 'No se pudo registrar la cuenta, por favor verifique los datos ingresados.')
    else:
        form = CuentaForm()
    return render(request, 'cuentas/cuentas_form.html', {
        'form': form
    })

@login_required
def mis_cuentas(request):
    cuentas = request.user.cuentas_del_usuario.filter(estado='Activa')
    return render(request, 'cuentas/listado_de_cuentas.html',{'cuentas':cuentas})


class EditarCuenta(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Cuenta
    form_class = EditarCuentaForm
    template_name = 'cuentas/cuentas_editar.html'
    success_message = "La cuenta %(nombre)s se modificó correctamente."
    success_url = reverse_lazy('cuentas:listado_de_cuentas')

@login_required
def ver_cuenta(request, pk):
    cuenta = Cuenta.objects.get(id=pk)
    return render(request,'cuentas/ver_cuenta.html', {'cuenta':cuenta})

def getGraficArea(request, pk):
    transacciones = Transaccion.objects.all().filter(cuenta=pk,fecha__month=4)#, fecha__month=4
    transacciones = [ {'fecha':transaccion.fecha, 'saldo':transaccion.saldo_actual_cuenta} for transaccion in transacciones]
    return HttpResponse(json.dumps(transacciones,cls=DjangoJSONEncoder), content_type = "application/json")

templates/cuentas/cuentas_editar.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{{ form_evento.media }}
{% block title %} Editar cuenta {% endblock %}
{% block content %}
	<div class="container-fluid">
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Editar cuenta</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Editar cuenta</h6>
            </div>
            <div class="card-body">
				<form method="post">
					{% csrf_token %}
					{% bootstrap_form form %}
					<a href="{% url 'cuentas:listado_de_cuentas' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a>
					<button type="submit" class="btn btn-success btn-icon-split"><span class="icon text-white-50"><i class="fas fa-check"></i></span><span class="text">Guardar</span></button>
				</form>
			</div>
		</div>
	</div>

{% endblock %}

templates/cuentas/cuentas_form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{{ form_evento.media }}
{% block title %} Registrar cuenta {% endblock %}
{% block content %}
	<div class="container-fluid">
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Registrar cuenta</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Registrar cuenta</h6>
            </div>
            <div class="card-body">
				<form method="post">
					{% csrf_token %}
					{% bootstrap_form form %}
					<a href="{% url 'cuentas:listado_de_cuentas' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a>
					<button type="submit" class="btn btn-success btn-icon-split"><span class="icon text-white-50"><i class="fas fa-check"></i></span><span class="text">Guardar</span></button>
				</form>
			</div>
		</div>
	</div>

{% endblock %}

templates/cuentas/listado_de_cuentas.html
{% extends 'base/tables.html' %}
{% load bootstrap4 %}
{% block title %} Lista de cuentas {% endblock %}

{% block content %}
<!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Cuentas</h1>
          
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <div class="row">
                <div class="col align-items-left">
                  <h6 class="m-0 font-weight-bold text-primary">Lista de cuentas</h6>
                </div>
                <div class="col align-items-right">                  
                    <div class="align-items-right">
                      <span class="float-right">
                        <a href="{% url 'usuarios:inicio' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a> <a class="btn btn-success" href="{% url 'cuentas:registrar_cuenta' %}"> <span class="text"> <i class="fas fa-plus-circle"></i> Añadir Cuenta</span></a>
                      </span>
                    </div>                  
                </div>
              </div>              
            </div>
            <div class="card-body">
              
              <div class="table-responsive">
                <table class="table table-bordered dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Saldo</th>
                            <th scope="col">Tipo</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if cuentas  %}
                        {% for cuenta in cuentas  %}
                        <tr class="table-primary">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ cuenta.nombre }}</td>
                            <td>{{ cuenta.saldo }}</td>
                            <td>{{ cuenta.tipo }}</td>
                            <td width="20%">
                                <a class="btn btn-warning" href="{% url 'cuentas:ver_cuenta' cuenta.id %}"><i class="fas fa-eye"></i> Ver</a>
                                <a class="btn btn-info" href="{% url 'cuentas:editar_cuenta' cuenta.id %}"><i class="fas fa-edit"></i> Editar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                    <h1> No hay cuentas </h1>
                    {% endif %}
                    </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->

{% endblock %}

templates/cuentas/ver_cuenta.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block extrastatic %}
<style media="screen"></style>
{% endblock extrastatic %}{% block title %} Cuenta {{cuenta.nombre}} {% endblock %}

{% block content %}
<!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <br/>
          <div class="row">
            <div class="col align-items-left">
              <h1 class="h3 mb-2 text-gray-800">Cuenta: {{cuenta.nombre}}</h1>
            </div>
            <div class="col align-items-center">
              <span class="float-right">
                      <a href="{% url 'cuentas:listado_de_cuentas' %}" class="btn btn-primary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Volver</span></a>
                    </span> 
            </div>
          </div>
          
          <!-- Earnings Card Example -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-money-check"></i> Información</h6>
              </div>
              <div class="card-body">
                  <div class="row">
                    <div class="col">Tipo de Cuenta : {{cuenta.tipo}}</div>
                    <div class="col">Saldo Actual : $ <span id="{{cuenta.id}}">{{cuenta.saldo}}</span> </div>
                    <div class="col">Estado : {{cuenta.estado}}</div>
                  </div>
              </div>              
            </div>
                <div class="card shadow mb-4">
                  <!-- Card Header - Dropdown -->
                  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Resumen Mensual</h6>                    
                  </div>
                  <!-- Card Body -->
                  <div class="card-body">
                    <div class="chart-area">
                      <canvas id="myAreaChart"></canvas>
                    </div>
                  </div>
                </div>

        <!-- /.container-fluid -->



{% endblock content %}


{% block extrajs %}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<!--<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>-->
<script type="text/javascript">
  function number_format(number, decimals, dec_point, thousands_sep) {
      // *     example: number_format(1234.56, 2, ',', ' ');
      // *     return: '1 234,56'
      number = (number + '').replace(',', '').replace(' ', '');
      var n = !isFinite(+number) ? 0 : +number,
        prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
        sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
        dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
        s = '',
        toFixedFix = function(n, prec) {
          var k = Math.pow(10, prec);
          return '' + Math.round(n * k) / k;
        };
      // Fix for IE parseFloat(0.55).toFixed(0) = 0;
      s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
      if (s[0].length > 3) {
        s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
      }
      if ((s[1] || '').length < prec) {
        s[1] = s[1] || '';
        s[1] += new Array(prec - s[1].length + 1).join('0');
      }
      return s.join(dec);
    }
  $(document).ready(function(){
    let saldo = (document.getElementById("{{cuenta.id}}").innerHTML);
    document.getElementById("{{cuenta.id}}").innerHTML = number_format(parseInt(saldo));
      $.get("{% url 'cuentas:getGraficArea' cuenta.id %}", function(data) {
          console.log(data)
          labelsIn=[]
          dataIn=[]
          for (var i = 0; i < data.length; i++) {
            labelsIn.push(data[i].fecha);
            dataIn.push(data[i].saldo);
          }
          var ctx = document.getElementById("myAreaChart");
          var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: labelsIn,
              datasets: [{
                label: "Saldo",
                lineTension: 0.3,
                backgroundColor: "rgba(78, 115, 223, 0.05)",
                borderColor: "rgba(78, 115, 223, 1)",
                pointRadius: 3,
                pointBackgroundColor: "rgba(78, 115, 223, 1)",
                pointBorderColor: "rgba(78, 115, 223, 1)",
                pointHoverRadius: 3,
                pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
                pointHoverBorderColor: "rgba(78, 115, 223, 1)",
                pointHitRadius: 10,
                pointBorderWidth: 2,
                data: dataIn,
              }],
            },
            options: {
              maintainAspectRatio: false,
              layout: {
                padding: {
                  left: 10,
                  right: 25,
                  top: 25,
                  bottom: 0
                }
              },
              scales: {
                xAxes: [{
                  time: {
                    unit: 'date'
                  },
                  gridLines: {
                    display: false,
                    drawBorder: false
                  },
                  ticks: {
                    maxTicksLimit: 7
                  }
                }],
                yAxes: [{
                  ticks: {
                    maxTicksLimit: 5,
                    padding: 10,
                    // Include a dollar sign in the ticks
                    callback: function(value, index, values) {
                      return '$' + number_format(value);
                    }
                  },
                  gridLines: {
                    color: "rgb(234, 236, 244)",
                    zeroLineColor: "rgb(234, 236, 244)",
                    drawBorder: false,
                    borderDash: [2],
                    zeroLineBorderDash: [2]
                  }
                }],
              },
              legend: {
                display: false
              },
              tooltips: {
                backgroundColor: "rgb(255,255,255)",
                bodyFontColor: "#858796",
                titleMarginBottom: 10,
                titleFontColor: '#6e707e',
                titleFontSize: 14,
                borderColor: '#dddfeb',
                borderWidth: 1,
                xPadding: 15,
                yPadding: 15,
                displayColors: false,
                intersect: false,
                mode: 'index',
                caretPadding: 10,
                callbacks: {
                  label: function(tooltipItem, chart) {
                    var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
                    return datasetLabel + ': $' + number_format(tooltipItem.yLabel);
                  }
                }
              }
            }
          });
    });      
  });
</script>


  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  


{% endblock extrajs %} 