apps/cuentas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='cuentas'

urlpatterns = [

    url(regex=r"^registrar$", view=crear_cuenta, name="registrar_cuenta"),
    url(regex=r"^listado$", view=mis_cuentas, name="listado_de_cuentas"),
    url(r'^editar/(?P<pk>\d+)/$', view=EditarCuenta.as_view(), name='editar_cuenta'),
    url(r'^ver/(?P<pk>\d+)/$', view=ver_cuenta, name='ver_cuenta'),
    url(r'^getGraficArea/(?P<pk>\d+)/$', view=getGraficArea, name="getGraficArea"),
]

apps/presupuestos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='presupuestos'

urlpatterns = [

    url(regex=r"^registrar$", view=crear_presupuesto, name="registrar_presupuesto"),
    url(regex=r"^listado$", view=mis_presupuestos, name="listado_de_presupuestos"),
    url(r'^editar/(?P<pk>\d+)/$', view=EditarPresupuesto.as_view(), name='editar_presupuesto'),
    url(r'^desactivar/(?P<id_presupuesto>\d+)/$', view=desactivar_presupuesto, name='desactivar_presupuesto'),
    url(regex=r"^registrar_categoria/(?P<id_presupuesto>[\w-]+)$", view=crear_categoria, name="registrar_categoria"),
    url(regex=r"^listado_de_categorias/(?P<id_presupuesto>[\w-]+)$", view=listado_de_categorias_del_presupuesto, name="listado_de_categorias"),
    url(regex=r"^editar_categoria/(?P<pk>[\w-]+)$", view=EditarCategoriaF, name="editar_categoria"),
]

apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from .views import *

app_name='usuarios'

urlpatterns = [
    url('signup', signup, name='signup'),
    url('inicio', view=Inicio, name='inicio'),
    path('cuentas_y_saldo', vista_cuentas_y_saldo, name="cuentas_y_saldo"),
    path('cuentas_y_saldo_json', cuentas_y_saldo_json, name="cuentas_y_saldo_json"),
    path('getGraficPie', view=getGraficPie, name="getGraficPie"),
    path('getCuentas', view=getCuentas, name="getCuentas"),
    ]

ds2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include, handler404
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include ('apps.cuentas.urls', namespace='cuentas')),
    path('presupuestos/', include ('apps.presupuestos.urls', namespace='presupuestos')),
    path('usuarios/', include ('apps.usuarios.urls', namespace='usuarios')),
    path('transacciones/', include ('apps.transacciones.urls', namespace='transacciones')),

    path('', views.LoginView.as_view(), name='home' ),
    url(r'^accounts/', include('allauth.urls'), name='accounts'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),   

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
	pass

apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

apps/usuarios/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, TemplateView
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from functools import wraps
from chartjs.views.lines import BaseLineChartView
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.core.serializers import serialize


from apps.usuarios.forms import SignUpForm
from apps.usuarios.models import User
from apps.cuentas.models import Cuenta
from apps.presupuestos.models import *

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user= form.save(commit=False)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user.es_cliente =True
            user.save()
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('usuarios:inicio')
    else:
        form = SignUpForm()
    return render(request, 'usuarios/signup.html', {'form': form})

def Inicio(request):
    cuentas = request.user.cuentas_del_usuario.filter(estado='Activa')
    presupuestos = request.user.presupuestos_del_usuario.filter(estado="Activo")#mes__month=3
    contexto = {'cuentas':cuentas,'presupuestos':presupuestos}
    print("inicio")
    print(contexto) 
    return render(request,'usuarios/inicio.html', {'cuentas':cuentas,'presupuestos':presupuestos})

def presupuestos_serialize(presupuesto):
    categorias = presupuesto.categorias_del_presupuesto.all()
    categorias = [ {'categoria_nombre': categoria.nombre, 'categoria_planeado': categoria.planeado, 'categoria_actual':categoria.actual} for categoria in categorias]
    return {'id':presupuesto.id,'nombre':presupuesto.nombre, 'total_planeado':presupuesto.total_planeado, 'total_actual':presupuesto.total_actual, 'categorias':categorias}

def getGraficPie(request):
    presupuestos = request.user.presupuestos_del_usuario.filter(estado="Activo")
    presupuestos = [ presupuestos_serialize(presupuesto) for presupuesto in presupuestos ]
    return HttpResponse(json.dumps(presupuestos,cls=DjangoJSONEncoder), content_type = "application/json")

def getCuentas(request):
    cuentas = request.user.cuentas_del_usuario.filter(estado='Activa')
    cuentas = [ {'cuenta_id':cuenta.id} for cuenta in cuentas ]
    return HttpResponse(json.dumps(cuentas,cls=DjangoJSONEncoder), content_type = "application/json")

class CuentasSaldo(BaseLineChartView):

    def get_labels(self):
        nombres_cuentas = list(Cuenta.objects.filter(usuario=1).values_list("nombre", flat=True))
        return nombres_cuentas

    def get_providers(self):
        return [" NOTHING "]

    def get_data(self):
        cuentas = Cuenta.objects.all()
        saldo_cuentas = []
        for cuenta in cuentas:
            saldo_cuenta = cuenta.saldo
            saldo_cuentas.append(saldo_cuenta)
        return [saldo_cuentas]

vista_cuentas_y_saldo = TemplateView.as_view(template_name='usuarios/inicio.html')
cuentas_y_saldo_json = CuentasSaldo.as_view()

templates/usuarios/editar_usuario.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{{ form_evento.media }}
{% block title %} Editar cliente {% endblock %}
{% block content %}
  <div class="container-fluid">
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Editar cliente</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Editar cliente</h6>
            </div>
            <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-success">Guardar</button>
          <a href="{% url 'usuarios:listado_de_clientes' %}" class="btn btn-primary">Volver</a>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/usuarios/inicio.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block extrastatic %}
<style media="screen"></style>
{% endblock extrastatic %}{% block title %} Inicio {% endblock %}

{% block content %}
<!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <br/>
          <!--<h1 class="h3 mb-2 text-gray-800">Inicio</h1>-->
          <!-- Earnings Card Example -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><a href=" {% url 'cuentas:listado_de_cuentas' %} "><i class="fas fa-money-check"></i> Cuentas </a></h6>
              </div>
              <div class="card-body">
                  {% if cuentas  %}
                    <div class="row">
                    {% for cuenta in cuentas  %}
                      <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                          <div class="card-body">
                            <div class="row no-gutters align-items-center">
                              <div class="col mr-2">
                                <div class="text-x font-weight-bold text-primary text-uppercase mb-1"><a href=" {% url 'cuentas:ver_cuenta' cuenta.id %} ">{{cuenta.nombre}}</a></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">$ <span id="{{cuenta.id}}">{{cuenta.saldo}}</span></div>
                              </div>
                              <div class="col-auto">
                                <i class="fas fa-dollar-sign fa-2x text-success"></i>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  {% else %}
                  <h2> No hay cuentas, registre su primera cuenta dando <a href="/cuentas/registrar">click aquí</a></h2>
                  {% endif %}
                </div>
              </div>              
            </div>

            <!-- PRESUPUESTOS -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'presupuestos:listado_de_presupuestos' %}"><i class="fas fa-search-dollar"></i> Presupuestos </a></h6>
              </div>
              <div class="card-body">
                  {% if presupuestos  %}
                    <div class="row">
                    {% for presupuesto in presupuestos %}
                      <!-- Donut Chart -->
                      <div class="col">
                        <div class="card shadow mb-4">
                          <!-- Card Header - Dropdown -->
                          <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">{{presupuesto.nombre}} </h6>
                          </div>
                          <!-- Card Body -->
                          <div class="card-body">
                            <div class="row">
                              <div class="col">
                                <h6 class=" font-weight-bold">Total Actual: $ <span id="{{presupuesto.id}}_actual"> {{presupuesto.total_actual}}</span></h6>
                              </div>
                              <div class="col">
                                <h6 class=" font-weight-bold"><span class="float-left"> Total Planeado: $ <span id="{{presupuesto.id}}_planeado"> {{presupuesto.total_planeado}}</span></span></h6>
                              </div>
                              
                            </div>
                            <div class="row">                              
                              <div class="col">
                                <div id=body_{{presupuesto.nombre}}>
                                  
                                  <h4 class="small font-weight-bold">Progreso:</h4>
                                </div>
                              </div>
                              <div class="col">
                                <div class="chart-pie pt-4">
                                  <canvas id="{{presupuesto.nombre}}"></canvas>
                                </div>
                                <div class="mt-4 text-center small" id="{{presupuesto.nombre}}_{{presupuesto.total_planeado}}">
                                </div>
                              </div>                             
                               
                              <!--<div class="progress mb-4">
                                <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" ></div>
                              </div>--> 
                            </div>                          
                          </div>
                        </div>
                      </div>
                      <!-- donutChart-->
                    {% endfor %}
                  {% else %}
                  <h2> No hay presupuestos, registre su primer presupuesto dando <a href="/presupuestos/registrar">click aquí</a> </h2>
                  {% endif %}
                </div>
              </div>              
            </div>
          <div class="row">
          </div>

{% endblock content %}


{% block extrajs %}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'js/number_format.js' %}"></script>
<!--<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>-->
<script type="text/javascript">
  $(document).ready(function(){
    $.get('{% url "usuarios:getCuentas" %}', function(data){
      for (var i = 0; i < data.length; i++) {
        let saldo = (document.getElementById(data[i].cuenta_id).innerHTML);
        document.getElementById(data[i].cuenta_id).innerHTML = number_format(parseInt(saldo));
      }
    });
    $.get('{% url "usuarios:getGraficPie" %}', function(data) {
      console.log(data);
          var colors = ["primary","success","info","warning","danger","secondary"]
          for (var i = 0; i < data.length; i++) {
            let actual = (document.getElementById(data[i].id+"_actual").innerHTML);
            document.getElementById(data[i].id+"_actual").innerHTML = number_format(parseInt(actual));
            let planeado = (document.getElementById(data[i].id+"_planeado").innerHTML);
            document.getElementById(data[i].id+"_planeado").innerHTML = number_format(parseInt(planeado));
            var ctx = document.getElementById(data[i].nombre);
            var tamañoCategoria = data[i].categorias.length;
            var labelsIn = []
            var dataIn = []
            for (var x = 0; x < tamañoCategoria; x++) {
              labelsIn.push(data[i].categorias[x].categoria_nombre);
              dataIn.push(data[i].categorias[x].categoria_planeado);              
              var addDiv = $(document.getElementById(data[i].nombre+"_"+data[i].total_planeado));
              $(addDiv).append(" <span class='mr-2'><i class='fas fa-circle text-"+colors[x]+"'></i> "+data[i].categorias[x].categoria_nombre+"</span>");
              var addProgress = $(document.getElementById("body_"+data[i].nombre));
              var porcentaje = data[i].categorias[x].categoria_actual/data[i].categorias[x].categoria_planeado
              porcentaje = Math.trunc(porcentaje*100)
              $(addProgress).append("<h4 class='small font-weight-bold'>"+data[i].categorias[x].categoria_nombre+"<span class='float-right'>"+porcentaje+"%</span></h4>");
              $(addProgress).append("<div class='progress mb-4'><div class='progress-bar bg-"+colors[x]+"' role='progressbar' style='width: "+porcentaje+"%' aria-valuenow='0' aria-valuemin='0' aria-valuemax='100' ></div></div>");
            }
            new Chart(ctx, {
              type:'doughnut',
              data:{
                labels: labelsIn,
                datasets: [{
                  data: dataIn,
                  backgroundColor: ['#4e73df', '#1cc88a', '#36b9cc','#f6c23e','#e74a3b','#858796'],
                  hoverBackgroundColor: ['#2e59d9', '#17a673', '#2c9faf'],
                  hoverBorderColor: "rgba(234, 236, 244, 1)",
                }],
              },
              options: {
                maintainAspectRatio: false,
                tooltips: {
                  backgroundColor: "rgb(255,255,255)",
                  bodyFontColor: "#858796",
                  borderColor: '#dddfeb',
                  borderWidth: 1,
                  xPadding: 15,
                  yPadding: 15,
                  displayColors: false,
                  caretPadding: 10,
                },
                legend: {
                  display: false
                },
                cutoutPercentage: 80,
              },
            });
          }
          
      });
  });
  
</script>


  <!-- Page level plugins -->



{% endblock extrajs %}

templates/usuarios/listado_clientes.html
{% extends 'base/tables.html' %}
{% load bootstrap4 %}
{% block title %} Lista de clientes {% endblock %}

{% block content %}
<!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <br/>
          <h1 class="h3 mb-2 text-gray-800">Lista de clientes</h1>
          <br/>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Lista de clientes</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Usuario</th>
                            <th scope="col">Nombres</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">Correo</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if object_list  %}
                        {% for usuario in object_list  %}
                        <tr class="table-primary">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ usuario.username }}</td>
                            <td>{{ usuario.first_name }}</td>
                            <td>{{ usuario.last_name }}</td>
                            <td>{{ usuario.email }}</td>
                            <td>
                                <a class="btn btn-warning" href="{% url 'usuarios:editar_usuario' usuario.id %}">Editar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                    <h1> No hay eventos </h1>
                    {% endif %}
                    </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->
{% endblock %}

templates/usuarios/signup.html
{% load staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'img/wallet.png' %}" type="image/gif" sizes="16x16">

  <title> Crea tu cuenta </title>
  <!-- Custom fonts for this template-->
  <link href=" {% static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
   <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href=" {% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">


</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block" style="background-image: url({% static 'img/loginbg.jpg' %})">
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Crea tu cuenta</h1>
              </div>  
              <form method="post">
      			    {% csrf_token %}
                {% include 'base/messages.html' %}
      			    {% bootstrap_form form %}
      			    <button type="submit" class="btn btn-success">Regístrate</button>
      			  </form>
              <hr>
              <div class="text-center">
                <a class="small" href="{% url 'login' %}">Tienes una cuenta? Inicia sesión</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src=" {% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src=" {% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src=" {% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src=" {% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>